### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by Jorgeivan6** [ISCOUTB/DH-Gestion-Ganadero-#1]

**Comment by Miguel2807** [comment]
![Imagen Flutter](https://github.com/user-attachments/assets/276b0768-bfda-4ad2-8a21-bec09bca3aa4)

Entorno preparado para programar en Flutter

**Comment by Denubila** [comment]
![Image](https://github.com/user-attachments/assets/f7c4065c-b159-4dc2-bd7b-adfd438d6d16)

Empezamos el desarrollo con Flutter, preparamos el entorno y comenzamos a explorar el lenguaje de dart

**Comment by Jorgeivan6** [comment]
Entornos y Proyecto de prueba en flutter con el lenguaje dark

![Image](https://github.com/user-attachments/assets/a737a6c1-b960-46cc-a9d0-b9760062826d)


Comprobación de correcto funcionamiento  con Run Flutter doctor
The command validates that all components of a complete Flutter development environment for Windows.flutter doctor
![Image](https://github.com/user-attachments/assets/bd0f457d-b22e-46a0-8f8d-8e2dd786f095)

**Comment by Jorgeivan6** [comment]
prueba
