### ISSUE TITLE
Definir Wireframes de toda la aplicacion

### ISSUE THREAD

**Issue by Jorgeivan6** [ISCOUTB/DH-Gestion-Ganadero-#2]

**Comment by Denubila** [comment]
**Inicio de usuario**

Se hace un primer modelo del inicio de usuario para la aplicación de gestión ganadero. 

![Image](https://github.com/user-attachments/assets/9e073466-f984-4dea-bb28-3e70d1caa0f4)

Para este wireframe se han empezado a explorar opciones para el diseño y los colores. La pagina de inicio de usuario muestra un header, y un contenedor para los campos que tiene que llenar el usuario.

**Comment by Jorgeivan6** [comment]
El día de ayer, 13 de septiembre, nos reunimos todo el equipo en las horas de la tarde para realizar, entre todos, varios wireframes para nuestro proyecto, para dejar una idea clara de donde queremos llegar de momento.

- Primer Wiframe 1.0 ingreso de animales formulario:

![Image](https://github.com/user-attachments/assets/0b52f839-e9f8-4f75-8b83-830d46e17ef5)







- Segundo Wiframe 1.0 Pagina principal:

![Image](https://github.com/user-attachments/assets/3dfa47fb-31df-4da7-8bc2-de307fc216e5)

**Comment by Jorgeivan6** [comment]
Realizo el día 17 de septiembre el wiframe de gestión del sistema donde va pensado. El poder realizar las copias de seguridad y ver o descargar los reportes de errores del sistema.

Se tiene pensado un boton para poder descargar un archivo con los errores presentados en cada usuario o si no simplemente un reporte con los errores presentados, además de poder seleccionar donde estará guardada la copia de seguridad local y con qué frecuencia o intervalo quiere el usuario que se realice podrá seleccionar además la posibilidad de copias en la nube con buen internet.

En la parte izquierda nuestro logo, y a la derecha la opción de regresar a la página principal.

![Image](https://github.com/user-attachments/assets/dc8bd244-aa0f-481e-80f0-a8905ee6bef5)

**Comment by Jorgeivan6** [comment]
Realizo hoy 17 de septiembre el wireframe de lista de usuarios la cual solo tiene acceso el administrador en otras palabras el dueño de la finca, se tiene pensado en colocar botones con la posibilidad de eliminar o editar la información de los usuarios adema de poder agregarlos, incluso si desea puede dar su puesto como dueño de la finca a alguien más asignándolo como administrador, pero claro el administrador no se puede borrar así mismo tiene muchos conflictos por eso no aparecen sus botones de eliminar solo editar su propia información.

Wireframe web:

![Image](https://github.com/user-attachments/assets/9d985ef9-c23b-4bca-acff-497da334e703)

Wireframe movil:

![Image](https://github.com/user-attachments/assets/c371de3a-7419-486e-aa60-6793c35b5cfd)

**Comment by Jorgeivan6** [comment]
Realizo Hoy 17 de septiembre el wireframe de formulario de síntomas con el cual se busca que el usuario ingrese los datos de los síntomas que presenta el animal y diga como se encuentra actualmente, junto aproximadamente las horas que lleva presentando sintomas.

Wireframe para web
![Image](https://github.com/user-attachments/assets/00ed9460-d9c3-4d7b-92ae-6c3f0213785b)


Wireframe para movil

![Image](https://github.com/user-attachments/assets/9bb3d4f0-6d48-453d-a288-bf4146f944a2)

**Comment by Johan-G27** [comment]
![image](https://github.com/user-attachments/assets/77161255-3d99-475a-a358-377cc28a0d16)
Añado wireframe para crear la cuenta de los usuarios

**Comment by Jorgeivan6** [comment]
Realizo 18 de septiembre el wireframe del apartado de las notificaciones donde el usuario pueda ver con facilidad las notificaciones que tiene para ese día o ya vencidas, también de agregar una nueva notificación manualmente, y abajo la lista de las próximas vacunas y ver todas.

wireframe web

![Image](https://github.com/user-attachments/assets/0fde6e41-3c8e-4cf0-a08b-940aca8c31e6)


Wireframe movil 

![Image](https://github.com/user-attachments/assets/b4766f20-57d0-4842-9b06-071db7fc753f)

**Comment by Jorgeivan6** [comment]
Realizo Wiframe de formulario para agregar recordatorio de vacuna que el usuario desea agregar manualmente. ingresara el id de animal asociado a esa recordatorio y fecha que desea recibir la notificacion de la vacuna. 

Wireframe web

![Image](https://github.com/user-attachments/assets/bab6604d-0154-4c4e-adeb-7b3cb492e162)

Wireframe movil

![Image](https://github.com/user-attachments/assets/7b8f1b88-6a06-44c9-bd08-e43e83569d2f)

**Comment by jairoserrano** [comment]
Adelante, felicitaciones.
